name: Fetch Daily Active Users Data

on:
  schedule:
    # 每天 UTC 时间 00:00（北京时间 08:00）执行
    - cron: '0 0 * * *'
  # 允许手动触发工作流
  workflow_dispatch:

jobs:
  fetch-dau-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Fetch and process DAU data
        env:
          API_URL: "http://51.79.56.175:5231/getonlines"
        run: |
          # 创建Python脚本获取并处理数据
          cat > fetch_data.py << 'EOF'
          import requests
          import json
          import os
          from datetime import datetime

          api_url = os.environ.get('API_URL')
          try:
              # 获取数据
              response = requests.get(api_url, timeout=10)
              response.raise_for_status()
              data = response.json()
              
              # 提取total字段
              total_users = data.get('total', 'N/A')
              
              # 准备要保存的数据
              current_date = datetime.now().strftime("%Y-%m-%d")
              result = {
                  "date": current_date,
                  "total_users": total_users,
                  "timestamp": datetime.now().isoformat(),
                  "api_url": api_url
              }
              
              # 输出结果供后续步骤使用
              print(f"Total users: {total_users}")
              
              # 将结果写入文件
              with open('dau-data.json', 'w') as f:
                  json.dump(result, f, indent=2)
                  
          except Exception as e:
              print(f"Error fetching data: {e}")
              exit(1)
          EOF

          # 执行Python脚本
          python fetch_data.py

      - name: Commit and push if data changed
        run: |
          # 配置Git用户信息
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # 检查文件是否有变化
          git add dau-data.json
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update DAU data [$(date +'%Y-%m-%d %H:%M')]"
            git push
          fi

      - name: Upload data as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dau-data
          path: dau-data.json
